version: '3.7'
services:
    fathom:
        deploy:
            labels:
                - 'caddy.address=privacystats.searx.be privacystats.yewtu.be'
                - caddy.targetport=8080
                - caddy.proxy.transparent
                - caddy.gzip
                - com.ouroboros.enable=true
            placement:
                constraints:
                    - node.hostname == awslinuxdocker
            restart_policy:
                condition: any
        image: usefathom/fathom
        entrypoint: /env_secrets_expand.sh server
        healthcheck:
            test: "/usr/bin/wget --quiet --tries=1 --spider http://localhost:8080/ || exit 1"
            interval: 1m30s
            timeout: 10s
            retries: 3
            start_period: 10s
        environment:
            - "FATHOM_DATABASE_DRIVER=mysql"
            - "FATHOM_DATABASE_HOST=mariadb:3306"
            - "FATHOM_DATABASE_NAME=fathom"
            - "FATHOM_DATABASE_USER=fathom"
            - "FATHOM_DATABASE_PASSWORD=DOCKER-SECRET->fathomdbpasswd"
            - "FATHOM_SECRET=DOCKER-SECRET->fathomsecret"
            - "ENTRYPOINT=/app/fathom"
        secrets:
            - fathomdbpasswd
            - fathomsecret
        volumes:
            - '/data/env_secrets_expand.sh:/env_secrets_expand.sh:ro'
        networks:
            - database
networks:
    database:
        external:
            name: database_default
secrets:
    fathomdbpasswd:
        external: true
    fathomsecret:
        external: true