version: "3.7"
services:
    db:
        deploy:
            labels:
                - com.ouroboros.enable=true
            placement:
                constraints:
                    - node.hostname == azurewinluxdocker
            restart_policy:
                condition: any
        secrets:
            - NEXTCLOUD_DB_PASSWORD
        environment:
            MYSQL_RANDOM_ROOT_PASSWORD: "yes"
            MYSQL_DATABASE: nextcloud
            MYSQL_USER: nextcloud
            MYSQL_PASSWORD_FILE: /run/secrets/NEXTCLOUD_DB_PASSWORD
        image: mariadb
        healthcheck:
            test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
            interval: 1m30s
            timeout: 10s
            retries: 3
            start_period: 10s
        networks:
            - default
            - bridge
        volumes:
            - '/data/nextcloud/mariadb:/var/lib/mysql'
            - '/etc/localtime:/etc/localtime:ro'
    nextcloud:
        deploy:
            labels:
                - com.ouroboros.enable=true
                - caddy.address=nextcloud.unixfox.eu
                - caddy.targetport=8888
                - caddy.proxy.transparent
                - caddy.tls.dns=powerdns
            placement:
                constraints:
                    - node.hostname == azurewinluxdocker
            restart_policy:
                condition: any
        image: "benyanke/nextcloud"
        networks:
            - global
            - default
        environment:
            TZ: Europe/Brussels
            DOMAIN: nextcloud.unixfox.eu
            DB_TYPE: mysql
        volumes:
            - '/data/nextcloud/data:/data'
            - '/data/nextcloud/config:/config'
            - '/data/nextcloud/apps:/apps2'
            - '/data/nextcloud/themes:/themes'
            - '/etc/localtime:/etc/localtime:ro'
secrets:
    NEXTCLOUD_DB_PASSWORD:
        external: true
networks:
    default:
    global:
        external: true
    bridge:
        external: true