version: '3.7'
services:
    fail2ban:
        cap_add:
            - NET_ADMIN
            - NET_RAW
        container_name: fail2ban
        env_file:
            - ./fail2ban.env
        image: 'crazymax/fail2ban:latest'
        network_mode: host
        restart: always
        volumes:
            - '/var/log:/var/log:ro'
            - '/data/fail2ban:/data'