version: '3.7'
services:
    ouroboros:
        deploy:
            labels:
                - com.ouroboros.enable=true
            placement:
                constraints:
                    - 'node.role == manager'
            restart_policy:
                condition: any
        environment:
            - CLEANUP=true
            - INTERVAL=600
            - SELF_UPDATE=true
            - TZ=Europe/Brussels
            - SWARM=true
            - LOG_LEVEL=debug
        image: pyouroboros/ouroboros
        volumes:
            - '/var/run/docker.sock:/var/run/docker.sock'
            - '/etc/localtime:/etc/localtime:ro'
    prune:
        deploy:
            labels:
                - com.ouroboros.enable=true
            mode: global
            restart_policy:
                condition: any
                delay: 86400s
                max_attempts: 3650
        image: softonic/docker-system-prune
        volumes:
            - '/var/run/docker.sock:/var/run/docker.sock'
            - '/etc/localtime:/etc/localtime:ro'