version: '3.7'
services:
    powerdns:
        deploy:
            labels:
                - com.ouroboros.enable=true
                - caddy.address=api.dns.unixfox.eu
                - caddy.targetport=8081
                - caddy.proxy.transparent
                - 'caddy.log=/ /var/log/powerdnsapi.log {combined}'
            placement:
                constraints:
                    - node.hostname == awslinuxdocker
            restart_policy:
                condition: any
        entrypoint: /env_secrets_expand.sh
        environment:
            - MYSQL_HOST=mariadb
            - MYSQL_USER=powerdns
            - MYSQL_PASS=DOCKER-SECRET->PD_DB_PASSWORD
            - MYSQL_DB=powerdns
            - PDNS_API_KEY=DOCKER-SECRET->PD_API_KEY
            - ENTRYPOINT=/entrypoint.sh
        hostname: powerdns
        image: psitrax/powerdns
        networks:
            - global
            - bridge
        ports:
            -
                mode: host
                protocol: udp
                published: 53
                target: 53
            -
                mode: host
                protocol: tcp
                published: 53
                target: 53
        secrets:
            - PD_DB_PASSWORD
            - PD_API_KEY
        volumes:
            - '/data/env_secrets_expand.sh:/env_secrets_expand.sh:ro'
            - '/data/powerdns:/etc/pdns/conf.d:ro'
            - '/etc/localtime:/etc/localtime:ro'
    powerdns-admin:
        command: "gunicorn app:app"
        deploy:
            labels:
                - caddy.address=dns.unixfox.eu
                - caddy.targetport=80
                - caddy.proxy.transparent
                - 'caddy.log=/ /var/log/powerdnsadmin.log {combined}'
                - caddy.gzip
                - 'caddy.proxy.header_downstream_0=Content-Security-Policy "default-src ''none''; font-src ''self'' data: fonts.googleapis.com fonts.gstatic.com; script-src ''self'' ''unsafe-inline''; img-src * data:; object-src ''none''; style-src ''self'' fonts.googleapis.com ''unsafe-inline''; frame-src ''self''; connect-src *; form-action ''self''; base-uri ''self'';frame-ancestors ''self'';"'
                - 'caddy.proxy.header_downstream_1=X-Content-Type-Options nosniff'
                - 'caddy.proxy.header_downstream_2=X-Frame-Options DENY'
                - 'caddy.proxy.header_downstream_3=X-XSS-Protection "1; mode=block"'
                - 'caddy.proxy.header_downstream_4=referrer-policy "no-referrer, strict-origin-when-cross-origin"'
                - 'caddy.proxy.header_downstream_5=strict-transport-security "max-age=63072000; includeSubDomains; preload"'
                - caddy.filter_0=rule
                - caddy.filter_0.path=/
                - 'caddy.filter_0.search_pattern=type="text/javascript"'
                - caddy.filter_0.replacement=@/root/.caddy/nounce.html
                - com.ouroboros.enable=true
            placement:
                constraints:
                    - node.hostname == awslinuxdocker
            restart_policy:
                condition: any
        entrypoint: /env_secrets_expand.sh
        environment:
            - SECRET_KEY=DOCKER-SECRET->PDA_SECRET_KEY
            - SALT=DOCKER-SECRET->PDA_SALT
            - LOG_LEVEL=WARNING
            - LOG_FILE=logfile.log
            - SQLALCHEMY_DATABASE_URI=DOCKER-SECRET->PDA_SQLALCHEMY_DATABASE_URI
            - PDNS_HOST=powerdns
            - PDNS_API_KEY=DOCKER-SECRET->PD_API_KEY
            - ENTRYPOINT=/usr/local/bin/entrypoint.sh
        image: ngoduykhanh/powerdns-admin
        networks:
            - global
        secrets:
            - PDA_SECRET_KEY
            - PDA_SALT
            - PDA_SQLALCHEMY_DATABASE_URI
            - PD_API_KEY
        volumes:
            - '/data/powerdnsadmin/config.py:/powerdns-admin/config.py'
            - 'powerdns-admin-assets:/powerdns-admin/app/static'
            - 'powerdns-admin-assets2:/powerdns-admin/node_modules'
            - 'powerdns-admin-assets3:/powerdns-admin/logs'
            - '/data/env_secrets_expand.sh:/env_secrets_expand.sh:ro'
            - '/etc/localtime:/etc/localtime:ro'
networks:
    global:
        external: true
    bridge:
        external: true
secrets:
    PD_DB_PASSWORD:
        external: true
    PDA_SQLALCHEMY_DATABASE_URI:
        external: true
    PDA_SALT:
        external: true
    PDA_SECRET_KEY:
        external: true
    PD_API_KEY:
        external: true
volumes:
    powerdns-admin-assets: null
    powerdns-admin-assets2: null
    powerdns-admin-assets3: null
