---
- name: Install zerotier requirements
  apk:
    name: libgcc,libstdc++

- name: Download zerotier packages
  get_url:
    url: https://dl.unixfox.eu/AlpinePackages/x86_64/zerotier-one-1.4.6-r0.apk
    dest: /tmp/zerotier-one-1.4.6-r0.apk
  register: result
  until: result.size > 0 and result is succeeded
  retries: 2
  delay: 3

- name: Install Zerotier
  command: apk add --allow-untrusted /tmp/zerotier-one-1.4.6-r0.apk

- name: Install zerotier dependencies
  apk:
    name: zerotier-one-openrc,zerotier-one-doc
    repository: http://dl-cdn.alpinelinux.org/alpine/edge/community

- name: start and enable zerotier-one
  service:
    name: zerotier-one
    state: started
    enabled: yes

- name: Wait for zerotier-one to come up
  wait_for:
    path: /var/lib/zerotier-one/zerotier-one.port

- include: join_network.yml
- include: authorize_node.yml

- name: reboot because zerotier is strange
  reboot: