version: '3.7'
services:
    postgres:
        deploy:
            labels:
                - com.ouroboros.enable=true
            placement:
                constraints:
                    - node.hostname == oracledockerstandard
            restart_policy:
                condition: any
        healthcheck:
            test: ["CMD", "pg_isready", "-U", "postgres"]
            interval: 1m30s
            timeout: 10s
            retries: 3
            start_period: 10s
        image: postgres:alpine
        networks:
            - bridge
            - default
        volumes:
            - '/data/invidious/postgres:/var/lib/postgresql/data'
            - '/etc/localtime:/etc/localtime:ro'
    invidious:
        deploy:
            replicas: 5
            resources:
                limits:
                    memory: 400M
            labels:
                - 'caddy.address=yewtu.be www.yewtu.be'
                - caddy.targetport=3000
                - caddy.proxy.transparent
                - caddy.proxy.header_downstream=-server
                - 'caddy.proxy.header_downstream_1=X-Robots-Tag "noindex, nofollow"'
                - 'caddy.proxy.header_downstream_2=X-Content-Type-Options nosniff'
                - 'caddy.proxy.header_downstream_3=X-Frame-Options sameorigin'
                - 'caddy.proxy.header_downstream_4=X-XSS-Protection "1; mode=block"'
                - 'caddy.proxy.header_downstream_5=referrer-policy "same-origin"'
                - 'caddy.proxy.header_downstream_6=strict-transport-security "max-age=63072000; includeSubDomains; preload"'
                - 'caddy.proxy.header_downstream_7=content-security-policy "default-src blob: data: ''self'' https://yewtu.be https://privacystats.yewtu.be ''unsafe-inline'' ''unsafe-eval''; media-src blob: ''self'' https://yewtu.be https://*.googlevideo.com:443"'
                - 'caddy.log=/ /var/log/invidious.log "{combined} - {latency}"'
                - 'caddy.status_0=429 /api/v1/videos'
                - 'caddy.status_1=429 /api/v1/channels'
                - 'caddy.status_2=429 /api/v1/search'
                - 'caddy.status_3=429 /api/v1/mixes'
                - caddy.filter_0=rule
                - caddy.filter_0.path=/$$
                - caddy.filter_0.search_pattern=</body>
                - caddy.filter_0.replacement=@/root/.caddy/invidious/fathom.html
                - caddy.filter_1=rule
                - caddy.filter_1.path=/
                - caddy.filter_1.search_pattern=Invidious</a>
                - caddy.filter_1.replacement="YewTube</a>"
                - caddy.filter_2=rule
                - caddy.filter_2.path=/
                - caddy.filter_2.search_pattern=Invidious</title>
                - caddy.filter_2.replacement="YewTube</title>"
                - com.ouroboros.enable=true
            placement:
                constraints:
                    - node.hostname == oracledockerstandard
            restart_policy:
                condition: any
        healthcheck:
            test: "curl --fail http://localhost:3000/ || exit 1"
            interval: 30s
            timeout: 10s
            retries: 3
            start_period: 1s
        image: flourgaz/invidious
        networks:
            - default
            - bridge
        volumes:
            - '/etc/localtime:/etc/localtime:ro'
            - '/data/invidious/config.yml:/invidious/config/config.yml:ro'
networks:
    default:
    bridge:
        external: true