version: '3.7'
services:
    postgres:
        deploy:
            labels:
                - com.ouroboros.enable=true
            placement:
                constraints:
                    - node.hostname == oraclefree2
            restart_policy:
                condition: any
        healthcheck:
            test: ["CMD", "pg_isready", "-U", "postgres"]
            interval: 1m30s
            timeout: 10s
            retries: 3
            start_period: 10s
        secrets:
            - POSTGRES_PASSWD
        environment:
            POSTGRES_PASSWORD_FILE: /run/secrets/POSTGRES_PASSWD
        ports:
            - mode: host
              protocol: tcp
              published: 5432
              target: 5432
        image: postgres:alpine
        volumes:
            - '/data/postgres:/var/lib/postgresql/data'
            - '/etc/localtime:/etc/localtime:ro'
    mariadb:
        deploy:
            labels:
                - com.ouroboros.enable=true
            placement:
                constraints:
                    - node.hostname == awslinuxdocker
            restart_policy:
                condition: any
        environment:
            MYSQL_DATABASE: unixfox
        image: yobasystems/alpine-mariadb
        healthcheck:
            test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
            interval: 1m30s
            timeout: 10s
            retries: 3
            start_period: 10s
        networks:
            - bridge
            - default
        volumes:
            - '/data/mariadb:/var/lib/mysql'
            - '/etc/localtime:/etc/localtime:ro'
networks:
    default:
    bridge:
        external: true

secrets:
    POSTGRES_PASSWD:
        external: true