version: '3.7'
services:
    mariadb:
        deploy:
            labels:
                - com.ouroboros.enable=true
            placement:
                constraints:
                    - node.role == manager
            restart_policy:
                condition: any
        environment:
            MYSQL_DATABASE: unixfox
        image: yobasystems/alpine-mariadb
        networks:
            - bridge
            - global
        volumes:
            - '/data/mariadb:/var/lib/mysql'
            - '/etc/localtime:/etc/localtime:ro'
networks:
    global:
        external: true
    bridge:
        external: true