---
- name: create syncthing directory
  file: 
    path: /opt/syncthing
    state: directory

- name: create main data directory
  file: 
    path: /data
    state: directory

- name: create log caddy directory
  file: 
    path: /var/log/caddy
    state: directory