version: '3.7'
services:
    vscode:
        image: unixfox/code-server
        deploy:
            labels:
                - com.ouroboros.enable=true
                - caddy.address=code.unixfox.eu
                - caddy.targetport=8080
                - caddy.proxy.transparent
                - caddy.proxy.websocket
                - caddy.jwt.path=/
                - caddy.jwt.redirect=/login
                - caddy.jwt.allow=sub unixfox
                - caddy.login.success_url=/
                - 'caddy.login.github=client_id=0be63859809f40d5e2b0,client_secret=3fc95dfcf1bfa321ec202281b75a27090fe56bde'
                - caddy.login.jwt_expiry=24h
                - caddy.login.cookie_expiry=24h
            placement:
                constraints:
                    - node.hostname == awsfakewinlux
            restart_policy:
                condition: any
        networks:
            - global
        volumes:
            - '/data/vscode:/home/coder/project'
            - '/data/vscodeshare:/home/coder/.local/share/code-server'
networks:
    global:
        external: true