version: '3.7'
services:
    vscode:
        image: unixfox/code-server
        command: "--auth none --disable-updates"
        deploy:
            labels:
                - com.ouroboros.enable=true
                - caddy.address=code.unixfox.eu
                - caddy.targetport=8080
                - caddy.proxy.transparent
                - caddy.proxy.websocket
                - caddy.jwt.path=/
                - caddy.jwt.redirect=/login
                - caddy.jwt.allow=sub unixfox
                - caddy.login.success_url=/
                - 'caddy.login.github=client_id=0be63859809f40d5e2b0,client_secret={%CODING_GITHUB_CLIENT_SECRET%}'
                - caddy.login.jwt_expiry=24h
                - caddy.login.cookie_expiry=24h
                - caddy.tls.dns=powerdns
            placement:
                constraints:
                    - node.hostname == awsfakewinlux
            restart_policy:
                condition: any
        healthcheck:
            test: "curl --fail http://localhost:8080/ || exit 1"
            interval: 1m30s
            timeout: 10s
            retries: 3
            start_period: 10s
        networks:
            - proxy_aws
        volumes:
            - '/data/vscode:/home/coder/project'
            - '/data/vscodeshare:/home/coder/.local/share/code-server'
networks:
    proxy_aws:
        external: true