version: '3.7'
services:
    caddy:
        command: '-email contact@emiliendevos.be -agree=true -log stdout'
        deploy:
            labels:
                - com.ouroboros.enable=true
            placement:
                constraints:
                    - 'node.role == manager'
            resources:
                reservations:
                    cpus: '0.1'
                    memory: 200M
            restart_policy:
                condition: any
        image: 'unixfox/caddy-docker-proxy:ci-alpine'
        networks:
            - global
            - bridge
        ports:
            -
                mode: host
                protocol: tcp
                published: 80
                target: 80
            -
                mode: host
                protocol: tcp
                published: 8080
                target: 8080
            -
                mode: host
                protocol: tcp
                published: 443
                target: 443
        volumes:
            - '/var/run/docker.sock:/var/run/docker.sock'
            - '/data/caddy:/root/.caddy'
            - '/var/log/caddy:/var/log'
            - '/etc/localtime:/etc/localtime:ro'
            - '/data/caddy/updateipv6:/updateipv6:ro'
    php:
        deploy:
            labels:
                - com.ouroboros.enable=true
            placement:
                constraints:
                    - node.labels.cloud==aws
                    - node.labels.os==linux
            restart_policy:
                condition: any
        volumes:
            - '/etc/localtime:/etc/localtime:ro'
        image: 'php:fpm'
        networks:
            - global
networks:
    global:
        external: true
    bridge:
        external: true