version: "3.7"
services:
    caddy:
        command: "-agree=true -log stdout -docker-validate-network=false"
        deploy:
            placement:
                constraints:
                    - node.labels.cloud!=aws
            resources:
                limits:
                    cpus: '0.1'
                    memory: 200M
            mode: global
            labels:
                - com.ouroboros.enable=true
            restart_policy:
                condition: any
        image: "unixfox/caddy-docker-proxy:ci-alpine"
        entrypoint: /env_secrets_expand.sh
        environment:
            - DOCKER_API_VERSION=1.37
            - DOCKER_HOST=tcp://socket:2375
            - CADDY_CLUSTERING=redis
            - CADDY_CLUSTERING_REDIS_HOST=redis
            - PDNS_API_URL=http://powerdns:8081
            - PDNS_API_KEY=DOCKER-SECRET->PD_API_KEY
            - CODING_GITHUB_CLIENT_SECRET=DOCKER-SECRET->CODING_GITHUB_CLIENT_SECRET
            - ENTRYPOINT=/bin/caddy
        networks:
            - proxy_global
            - bridge
            - socket
            - default
            - proxy_aws
            - torrent
        secrets:
            - CODING_GITHUB_CLIENT_SECRET
            - PD_API_KEY
        ports:
            - mode: host
              protocol: tcp
              published: 80
              target: 80
            - mode: host
              protocol: tcp
              published: 8080
              target: 8080
            - mode: host
              protocol: tcp
              published: 443
              target: 443
        volumes:
            - "/data/caddy:/root/.caddy"
            - "/var/log/caddy:/var/log"
            - "/etc/localtime:/etc/localtime:ro"
            - "/data/env_secrets_expand.sh:/env_secrets_expand.sh:ro"
    socket:
        image: alpine/socat
        networks:
            - socket
        command: tcp-listen:2375,fork,reuseaddr unix-connect:/var/run/docker.sock
        deploy:
            labels:
                - com.ouroboros.enable=true
            placement:
                constraints:
                    - "node.role == manager"
            restart_policy:
                condition: any
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:ro
    redis:
        image: redis:alpine
        networks:
            - default
        volumes:
            - "/data/redis:/data"
        deploy:
            placement:
                constraints:
                    - node.hostname == mx.emiliendevos.be
            restart_policy:
                condition: any
    # php:
    #     deploy:
    #         labels:
    #             - com.ouroboros.enable=true
    #         placement:
    #             constraints:
    #                 - node.hostname == azurelinuxdocker
    #         restart_policy:
    #             condition: any
    #     volumes:
    #         - "/etc/localtime:/etc/localtime:ro"
    #     image: "php:fpm"
    #     networks:
    #         - global

secrets:
    PD_API_KEY:
        external: true
    CODING_GITHUB_CLIENT_SECRET:
        external: true

networks:
    proxy_global:
        name: proxy_global
    proxy_aws:
        external: true
    torrent:
        external: true
        name: torrent_default
    socket:
        external: true
    default:
    bridge:
        external: true