version: '3.7'
services:
    antibot:
        deploy:
            labels:
                - 'caddy.address=searx.be www.searx.be'
                - caddy.targetport=3000
                - caddy.proxy.transparent
                - 'caddy.log_0=/ /var/log/searx.log "{combined} - {latency}"'
                - 'caddy.log_1=/ /var/log/searx_fail2ban.log "{when_unix} {remote} {status}"'
                - 'caddy.status=403 /deny'
                - caddy.proxy.header_downstream=-server
                - 'caddy.proxy.header_downstream_0=Content-Security-Policy "default-src ''none''; font-src ''self'' data:; script-src ''self'' ''nonce-upaek0pieKu'' stats.unixfox.eu; img-src * data:; object-src ''none''; style-src ''self'' ''unsafe-inline''; frame-src ''self''; connect-src *; form-action ''self''; base-uri ''self'';frame-ancestors ''self'';"'
                - 'caddy.proxy.header_downstream_1=X-Content-Type-Options nosniff'
                - 'caddy.proxy.header_downstream_2=X-Frame-Options DENY'
                - 'caddy.proxy.header_downstream_3=X-XSS-Protection "1; mode=block"'
                - 'caddy.proxy.header_downstream_4=referrer-policy "no-referrer, strict-origin-when-cross-origin"'
                - 'caddy.proxy.header_downstream_5=strict-transport-security "max-age=63072000; includeSubDomains; preload"'
                - caddy.filter_0=rule
                - caddy.filter_0.path=/
                - caddy.filter_0.search_pattern=</body>
                - caddy.filter_0.replacement=@/root/.caddy/searx/stats.html
                - caddy.filter_1=rule
                - caddy.filter_1.path=/
                - 'caddy.filter_1.search_pattern=type="text/javascript"'
                - caddy.filter_1.replacement=@/root/.caddy/nounce.html
                - caddy.filter_2=rule
                - caddy.filter_2.path=/
                - caddy.filter_2.search_pattern=<head>
                - caddy.filter_2.replacement=@/root/.caddy/searx/opengraph.html
                - caddy.filter_3=rule
                - caddy.filter_3.path=/
                - caddy.filter_3.search_pattern=<head>
                - caddy.filter_3.replacement=@/root/.caddy/searx/fake.html
                - caddy.ipfilter=/
                - caddy.ipfilter.rule=block
                - caddy.ipfilter.prefix_dir=/root/.caddy/searx/jail
                - caddy.rewrite_0=/
                - 'caddy.rewrite_0.if_0={query} has "format=json"'
                - 'caddy.rewrite_0.if_1={query} has "format=csv"'
                - 'caddy.rewrite_0.if_2={query} has "format=rss"'
                - caddy.rewrite_0.if_op=or
                - caddy.rewrite_0.to=/deny
                - caddy.gzip
                - caddy.expires
                - 'caddy.expires.match=static/* 1w'
                - caddy.errors.403=/root/.caddy/errorspage/HTTP403.html
                - caddy.rewrite_1=/
                - 'caddy.rewrite_1.if={remote} is "5.9.58.49"'
                - caddy.rewrite_1.to=/about
                - com.ouroboros.enable=true
            placement:
                constraints:
                    - node.labels.cloud==aws
                    - node.labels.os==linux
            restart_policy:
                condition: any
        environment:
            - 'TARGET=http://searx:8888'
            - MAX_RETRY=1
            - JAIL_PATH=/jail
            - ENDPOINT_NAME=searx.css
            - TIMEOUT_LOAD=120000
            - 'WHITELIST=5.9.58.49,172.18.0.1,35.238.202.250,64.41.200.101,35.239.110.147,66.249.69.103,63.245.210.130,138.68.46.186,63.245.208.130'
        image: unixfox/antibot-proxy
        networks:
            - global
        volumes:
            - '/data/caddy/searx/jail:/jail'
            - '/etc/localtime:/etc/localtime:ro'
    searx:
        deploy:
            labels:
                - com.ouroboros.enable=true
            mode: global
            placement:
                constraints:
                    - node.labels.os==linux
            restart_policy:
                condition: any
        environment:
            - 'BASE_URL=https://searx.be'
            - PGID=0
            - PUID=0
        image: woahbase/alpine-searx
        networks:
            - global
        volumes:
            - '/data/searx/settings.yml:/data/settings.yml:ro'
            - '/etc/hosts:/etc/hosts:ro'
            - '/etc/localtime:/etc/localtime:ro'
            - '/data/searx/engines/google.py:/usr/local/searx/searx/engines/google.py:ro'
            - '/data/searx/engines/google_images.py:/usr/local/searx/searx/engines/google_images.py:ro'
            - '/data/searx/webapp.py:/usr/local/searx/searx/webapp.py:ro'
            - '/data/searx/templates/oscar/results.html:/usr/local/searx/searx/templates/oscar/results.html:ro'
networks:
    global:
        external: true
