version: "3.7"
services:
    filtron:
        deploy:
            labels:
                - "caddy.address=searx.be www.searx.be"
                - caddy.targetport=4004
                - caddy.proxy.transparent
                - 'caddy.log_0=/ /var/log/searx.log "{combined} - {latency}"'
                - 'caddy.log_1=/ /var/log/searx_fail2ban.log "{when_unix} {remote} {status}"'
                - "caddy.errors=/var/log/searx_errors.log"
                - "caddy.status=403 /deny"
                - caddy.proxy.header_downstream=-server
                - 'caddy.proxy.header_downstream_0=Content-Security-Policy "default-src ''none''; font-src ''self'' data:; script-src ''self''; img-src * data:; object-src ''none''; style-src ''self'' ''unsafe-inline''; frame-src ''self''; connect-src *; form-action ''self''; base-uri ''self'';frame-ancestors ''self'';"'
                - 'caddy.proxy.header_downstream_1=X-Content-Type-Options nosniff'
                - 'caddy.proxy.header_downstream_2=X-Frame-Options DENY'
                - 'caddy.proxy.header_downstream_3=X-XSS-Protection "1; mode=block"'
                - 'caddy.proxy.header_downstream_4=referrer-policy "strict-origin-when-cross-origin"'
                - 'caddy.proxy.header_downstream_5=strict-transport-security "max-age=63072000; includeSubDomains; preload"'
                - caddy.rewrite_0=/
                - 'caddy.rewrite_0.if_0={query} has "format=json"'
                - 'caddy.rewrite_0.if_1={query} has "format=csv"'
                - 'caddy.rewrite_0.if_2={query} has "format=rss"'
                - caddy.rewrite_0.if_op=or
                - caddy.rewrite_0.to=/deny
                - caddy.gzip
                - caddy.expires
                - "caddy.expires.match=static/* 1w"
                - caddy.errors.403=/root/.caddy/errorspage/HTTP403.html
                - com.ouroboros.enable=true
            placement:
                constraints:
                    - node.hostname == mx.emiliendevos.be
            restart_policy:
                condition: any
        image: dalf/filtron
        command: -listen 0.0.0.0:4004 -target searx:8888
        networks:
            - default
            - proxy_global
        volumes:
            - "/data/searx/filtron/rules.json:/etc/filtron/rules.json:rw"
            - "/etc/localtime:/etc/localtime:ro"
    searx:
        deploy:
            mode: global
            placement:
                constraints:
                    - node.labels.cloud!=aws
            labels:
                - com.ouroboros.enable=true
            restart_policy:
                condition: any
        environment:
            - "BASE_URL=https://searx.be"
            - PGID=0
            - PUID=0
        image: woahbase/alpine-searx
        networks:
            - default
        volumes:
            - "/data/searx/settings.yml:/data/settings.yml:ro"
            - "/etc/hosts:/etc/hosts:ro"
            - "/etc/localtime:/etc/localtime:ro"
            #- "/data/searx/engines/startpage.py:/usr/local/searx/searx/engines/startpage.py:ro"
            #- "/data/searx/engines/google.py:/usr/local/searx/searx/engines/google.py:ro"

networks:
    default:
    proxy_global:
        external: true
    global:
        external: true
    bridge:
        external: true
