---
- name: Replace repositories file
  copy:
    src: repositories
    dest: /etc/apk/repositories

- name: Update cache
  apk:
    update_cache: yes

- name: Update and upgrade system
  apk:
    available: yes
    upgrade: yes

- name: Install basic packages
  apk:
    name: bash,git,unzip,zip,curl,wget,sudo,htop,nano,python,glances

- name: Install apk autoupdate
  apk:
    name: apk-autoupdate
    repository: http://dl-cdn.alpinelinux.org/alpine/edge/testing

- name: Fix apk autoupdate
  lineinfile:
    dest: /usr/share/apk-autoupdate/functions.sh
    state: absent
    regexp: "-c"

- name: CRON apk autoupdate
  cron:
    name: "apk autoupdate"
    minute: "0"
    hour: "2"
    day: "*"
    month: "*"
    weekday: "*"
    user: root
    job: "/usr/sbin/apk-autoupdate"

- name: Config apk autoupdate
  template:
    src: apk-autoupdate.conf
    dest: /etc/apk/autoupdate.conf

- name: Fix IPv6
  sysctl:
    name: "{{ item }}"
    value: '0'
    sysctl_file: /etc/sysctl.d/ipv6-fix.conf
  with_items:
        - "net.ipv6.conf.all.accept_ra"
        - "net.ipv6.conf.all.autoconf"
        - "net.ipv6.conf.default.accept_ra"
        - "net.ipv6.conf.default.autoconf"
        - "net.ipv6.conf.eth0.accept_ra"
        - "net.ipv6.conf.eth0.autoconf"