version: "3.7"
services:
    rclone:
        command: "serve http --addr 0.0.0.0:80 --read-only --no-modtime arubaisocrypt:"
        deploy:
            labels:
                - caddy.address=dl.unixfox.eu
                - caddy.targetport=80
                - caddy.proxy.transparent
                - caddy.tls.dns=powerdns
                - com.ouroboros.enable=true
            placement:
                constraints:
                    - node.hostname == mx.emiliendevos.be
            restart_policy:
                condition: any
        healthcheck:
            test: "/usr/bin/wget --quiet --tries=1 --spider http://localhost:80/ || exit 1"
            interval: 1m30s
            timeout: 10s
            retries: 3
            start_period: 10s
        image: "unixfox/rclone-iso"
        networks:
            - proxy_aws
        volumes:
            - '/data/rclone:/config/rclone'

networks:
    proxy_aws:
        external: true